### ISSUE TITLE
Make new official release

### ISSUE THREAD

**Issue by SixParQuatre** [unitycoder/UnityLauncherPro#101]
I've been recommending this to some peep and a few have gotten  1.0.37 instead of 1.0.38 which has a ton of bugfixes/improvements that are great for newcomes. Would it be possible to make a new Release ?

**Comment by unitycoder** [comment]
yeah planning to do that very Soon,
just discovered some small issues still past few days, so havent done builds yet.

For future: need to look into adding automated tests.

**Comment by unitycoder** [comment]
thanks for the promotion, you pushed downloads to hit 1k total : D

**Comment by unitycoder** [comment]
definitely doing the main release within this year :)

**Comment by SixParQuatre** [comment]
I was going to say I've been on 1.0.39 for a month with no issue; so I think turning that into a release makes sense.
Plus, a new beta of Hub just came out so I've got a feeling there's going to be opportunities to recommend this to peepsl.

**Comment by unitycoder** [comment]
latest build
[1.0.42](https://github.com/unitycoder/UnityLauncherPro/releases/tag/1.0.42)
