### ISSUE TITLE
[Bug]Program crashes after using 'Remove from recent list' in Project Tab.

### ISSUE THREAD

**Issue by SixParQuatre** [unitycoder/UnityLauncherPro#102]
In: 1.0.38
This doesn't happen when doing that on the first project in the list.
When restarting, the project is properly gone from the list though.

**Comment by unitycoder** [comment]
added latest pre-release build, can check if that fixes your remove recent bug
https://github.com/unitycoder/UnityLauncherPro/releases/tag/1.0.39

**Comment by SixParQuatre** [comment]
It fixes the  crash but it introduced or highlighted[ another  issue](https://github.com/unitycoder/UnityLauncherPro/issues/104)

**Comment by unitycoder** [comment]
should be fixed on main builds now too
