### ISSUE TITLE
[Feature Request] Add 'Uninstall Version' in Editor Tab

### ISSUE THREAD

**Issue by SixParQuatre** [unitycoder/UnityLauncherPro#103]
It could be a button, or an option in the context menu.
I'm feeling the  need for this currently, because I'm updating to every new minor version of 2021.3 and need to uninstall older version because I'm running out of disk space.

**Comment by unitycoder** [comment]
context menu in Editors tab would be certainly easy first step.

(personally i just delete the unity folders when not needed, does unity have uninstaller actually?)

eventually would be nice to have the "upgrade" context menu and it would offer to install on top of that unity.

**Comment by SixParQuatre** [comment]
> context menu in Editors tab would be certainly easy first step.

> (personally i just delete the unity folders when not needed, does unity have uninstaller actually?)
Yes, they do! At least the one downloaded from their web  page... but  they take a while,
 
> eventually would be nice to have the "upgrade" context menu and it would offer to install on top of that unity.
That'd be great, but I think it would be not super useful because erm, Unity's patch release also tend to break stuff;  so I personally won't  upgrade and  delete at the  same time :)

**Comment by unitycoder** [comment]
ok, hub seems to run the silent "uninstaller.exe /S"
![image](https://user-images.githubusercontent.com/5438317/200664882-40cae5d8-2086-4d0d-bae6-3586ee6692aa.png)

and after that removes shortcuts, registrykeys, firewall rules.. i guess uninstall exe doesnt do that then?
![image](https://user-images.githubusercontent.com/5438317/200665070-8dcde001-d0ce-4ad3-94e2-347545e7eb32.png)
