### ISSUE TITLE
[Bug] Newly added projects disappear after closing the program if the user never opened them.

### ISSUE THREAD

**Issue by SixParQuatre** [unitycoder/UnityLauncherPro#104]
In 1.0.39.
Repro steps:
- add a new project using "Add Project.."
- close Unity Launcher Pro
- relaunch Unity Launcher Pro, notice the projects have disappeared.
As a  note, the path of the project also appear in red when adding them.

If the user open the project at least once, this doesn't happen.

**Comment by unitycoder** [comment]
yup, that part is not added yet,
- cannot easily insert into unity registry as first item, would need to bump all items +1 (and if another unity instance starts modifying registry at the same time, some items might go missing..)
- now with custom recent list, it would be possible to save into that, but only if user has enabled more than 40 recent projects..

so, open for ideas how to save it (without opening),
or maybe should just enable keep more than 40 projects by default?

**Comment by SixParQuatre** [comment]
I don't know if there are any bad side-effects of enabling 40 + projects by default; but if one is that you don't get parity with Unity Hub's own Project list, then I feel enabling it by default to get rid of the current behaviour would be a net gain - again, because it makes onboarding a more polish/predictable experience.

**Comment by unitycoder** [comment]
also one other option:
- If user closes launcher after adding, show warning that this project would be removed (but then again, not really user friendly, but at least would know why)

Also as comments:
- There should be no reason to close launcher (unless shutting down computer or by accident?)
- Would anyone add multiple projects through "Add project" and then not open them? (like personally i hardly ever use add projects, but instead open project in Explorer context menu. But i guess could imagine that after installing this launcher, they want to add some existing projects on top of the unity 40 items list..)

**Comment by SixParQuatre** [comment]
Once I had tested Unity Launcher Pro with one of my projects, I basically added all my local projects one by one to see which version they were at, etc... 
There were about 10 of them so I didn't open all of them there and then; but I expected them to stick in the list to  remind myself which one I had to upgrade.

**Comment by unitycoder** [comment]
ok makes sense.

for future ideas,
would you use drag n drop project folder into launcher window, to add projects? (have thought about it but not added)

**Comment by SixParQuatre** [comment]
That would be cool, even more so if you could drag and drop several root project folders.
Otherwise, a "Find Projects under Folder" may be useful as well - I store all of my projects under a specific folder and maybe other peeps do too ?

**Comment by unitycoder** [comment]
now defaults to 50 recent projects enabled
