### ISSUE TITLE
Double clicking on one of the header in the Projects tab opens Unity

### ISSUE THREAD

**Issue by Mythique** [unitycoder/UnityLauncherPro#106]
![image](https://user-images.githubusercontent.com/4488088/204843021-49e8e999-2170-4f80-be10-ae5e8335aa7a.png)

In the project tab double clicking on the header opens the currently highlighted Unity project. This can happen when :
- Wanting to sort by Project/Version/Path/... and clicking again to sort in the reverse order.
- Trying to resize a column when double clicking on a separator.

**Comment by unitycoder** [comment]
still happens on path and later headers (only project/version had disabled hittest)
