### ISSUE TITLE
download urls have changed for new releases (alpha/beta)

### ISSUE THREAD

**Issue by unitycoder** [unitycoder/UnityLauncherPro#108]
parser returns bad url, so download fails:
`exeURL= (unity-hub-link#version=2023.1.0a22)`

**Comment by SixParQuatre** [comment]
About that, the Release page now contains a direct link for the editor install (big 2.5+Gb); would it be possible to point to that ? It would better support pause/failure and resume; and would make cleaning up files easier.
FYI, the link is in the form of: 
https://download.unity3d.com/download_unity/7d24041b62ee/Windows64EditorInstaller/UnitySetup64-2023.1.0a23.exe
vs the one the program currently goes to:
https://beta.unity3d.com/download/7d24041b62ee/UnityDownloadAssistant.exe

**Comment by unitycoder** [comment]
ok, that might have to be separate button, or could be settings checkbox, to say which installer is preferred (full or web installer)?

downloading that would be better to do in Browser though,
since its so big file, browser can handle it better.. (in case of bad connection etc).

**Comment by unitycoder** [comment]
ah yes, the download & install also uses that assistant.exe (since it allows you to pick modules and features),
the full exe i think only installs main unity (need to install modules separately?)

the download in browser button could be actually removed or replaced with that full install button,
now that there is that "download & install"

**Comment by SixParQuatre** [comment]
Yep! though, I don't see "download & install" in 1.0.40; is that available only when building from source ?

**Comment by unitycoder** [comment]
should be fixed in main build now too
