### ISSUE TITLE
Can't find the installed version of Unity2021, maybe it can make it smarter~

### ISSUE THREAD

**Issue by zhaoguohao** [unitycoder/UnityLauncherPro#112]
![image](https://user-images.githubusercontent.com/43693203/210153767-3568cb42-fe20-44fa-83ce-27e1dea3ad00.png)

When I use Unity2021, it cannot find my Unity installation directory, because the installation directory of the Unity2021 version starts from the "Editor" file path by default, I need to add the path folder "Unity" before the 2021 installation directory, or use The upper layer of the default installation path, you can try to make a small optimization to make it smarter or add a small reminder~
Thanks dalao

**Comment by unitycoder** [comment]
Was that path set by you or unity hub installer?

but yes, it only scans for first level, not child folders.. (i dont think that will be added, as it would slow down the scanning)
I guess can try to improve guide/documentation for that.

**Comment by zhaoguohao** [comment]
> Was that path set by you or unity hub installer?
> 
> but yes, it only scans for first level, not child folders.. (i dont think that will be added, as it would slow down the scanning) I guess can try to improve guide/documentation for that.

The default setting when installing Unity, yes, you can add a prompt, or let the user directly select the folder containing Unity.exe

**Comment by unitycoder** [comment]
ok if its coming from hub, then i should add that..

whats the default path in hub settings?
![image](https://user-images.githubusercontent.com/5438317/210276705-2a4925a0-491f-428f-9d59-3335458ce69c.png)
