### ISSUE TITLE
[Bug] Toggling 'Show Git branch column' on doesnt refresh the project

### ISSUE THREAD

**Issue by SixParQuatre** [unitycoder/UnityLauncherPro#117]
Current behaviour:
- when going back to the projects tab, the column is visible but empty for all project
- after a manual refresh, the branch name appears
Desired behaviour:
- the projects are automatically refreshed when the option is toggled to on

**Comment by unitycoder** [comment]
i think same for other optional columns too, it doesn't force refresh, so need to add.
