### ISSUE TITLE
App Crash 

### ISSUE THREAD

**Issue by Bian-Sh** [unitycoder/UnityLauncherPro#12]
![image](https://user-images.githubusercontent.com/24520547/86530966-fd0a6700-beef-11ea-8407-272db6090bce.png)
see pic above ,Line 497  of "Tools.cs " have some unexpect array item.  
and I've found bug,cause you just replace "(64-bit)"   
![image](https://user-images.githubusercontent.com/24520547/86531083-de58a000-bef0-11ea-8e6f-4c3d550319c3.png)

**Comment by unitycoder** [comment]
in which unity installation that happens? or is that some 32bit unity version?

**Comment by Bian-Sh** [comment]
> in which unity installation that happens? or is that some 32bit unity version?

some 32bit unity version
