### ISSUE TITLE
[Suggestion] The refresh list operation should not rest the currently sorting column header

### ISSUE THREAD

**Issue by victor-kallai** [unitycoder/UnityLauncherPro#123]
On the Projects tab, when pressing on the Refresh List project, the list also resets the currently sorting column to be default sorted by "Modified" in descending order.
Ideally the last selected sorted column will be persisted when refreshing the list (and restarting the app), and it will keep the projects sorted in the same way.

**Comment by unitycoder** [comment]
yes, need to add that.

- [ ] save current sorting method to settings, when sort by column https://github.com/unitycoder/UnityLauncherPro/blob/a830670e572034db1f092fc82361bde368937c76/UnityLauncherPro/MainWindow.xaml.cs#L2910
- [ ] sort after refresh, if not using default sort(?) https://github.com/unitycoder/UnityLauncherPro/blob/a830670e572034db1f092fc82361bde368937c76/UnityLauncherPro/MainWindow.xaml.cs#L727
- [ ] app start (loadsettings), set current sort column
