### ISSUE TITLE
New/Custom App icons

### ISSUE THREAD

**Issue by unitycoder** [unitycoder/UnityLauncherPro#127]
TODO
- [ ]  Customizable icon (loads from file)
- [ ] OR few icons to select from (builtin)
- [ ] settings field to toggle this feature or to select builtin icon

There's pull request for app icon:
https://github.com/unitycoder/UnityLauncherPro/pull/126

![img](https://raw.githubusercontent.com/LTMX/UnityLauncherPro/master/UnityLauncherPro/Images/icon.png)
https://github.com/LTMX/UnityLauncherPro/blob/master/UnityLauncherPro/Images/icon.png

I wont easily merge icon changes (due to already being used to that simple box icon, which was just a temporary icon),
use this issue to collect icon ideas and comment on them.

And if there are many different ideas,
Probably it should be customizable at runtime (if thats possible in wpf app),
or app could include few icons to choose from in settings (easier, since icon file is the inside app).

current icon file is at
![img](https://raw.githubusercontent.com/unitycoder/UnityLauncherPro/master/UnityLauncherPro/Images/icon.png)
https://github.com/unitycoder/UnityLauncherPro/blob/master/UnityLauncherPro/Images/icon.png

**Comment by LTMX** [comment]
![ULP Pink White 2](https://user-images.githubusercontent.com/47640688/231088282-14927212-2273-4b55-8d66-e70b8c809d78.png)
![ULP Pink Black 2](https://user-images.githubusercontent.com/47640688/231088328-6a907799-486a-4ac6-a894-61503aa32790.png)
![ULP White_1](https://user-images.githubusercontent.com/47640688/231087891-11a5de75-5f62-4d76-ab7c-bee3dd434bd5.png)
![ULP Black 2](https://user-images.githubusercontent.com/47640688/231088246-5b4c28aa-af59-4d1e-9b0e-322839f7d8b5.png)

**Comment by LTMX** [comment]
![ULP White Blue](https://user-images.githubusercontent.com/47640688/231093446-e1cfd0d8-4c36-4e51-b275-07aeeba2e024.png)
![ULP White Blue 2](https://user-images.githubusercontent.com/47640688/231093457-694c8446-79a5-402d-80b7-1a50ee2d258a.png)
![ULP White Dark Violet](https://user-images.githubusercontent.com/47640688/231093472-5515359c-1366-4386-bff1-cbacee47a532.png)
![ULP White Dark Violet 2](https://user-images.githubusercontent.com/47640688/231093483-6157a985-1da7-47ff-b963-c50c39272501.png)

**Comment by unitycoder** [comment]
thanks! lets collect those ideas here, personally i'd prefer something that looks similar to unity style,
without breaking any TM of course.

Consider also that the task bar icon should look sharp,
![image](https://user-images.githubusercontent.com/5438317/231105499-ddabb066-2859-40c8-aab6-e2fa9808fb2c.png)

Not sure if there is also different look or size in Win11 icons?

**Comment by LTMX** [comment]
> thanks! lets collect those ideas here, personally i'd prefer something that looks similar to unity style, without breaking any TM of course.
> 
> Consider also that the task bar icon should look sharp, ![image](https://user-images.githubusercontent.com/5438317/231105499-ddabb066-2859-40c8-aab6-e2fa9808fb2c.png)
> 
> Not sure if there is also different look or size in Win11 icons?

(For anyone who would like to create custom icons)
Here is a good tutorial so .ico files support different sizes : https://www.wikihow.com/Create-a-Windows-Icon

**Comment by LTMX** [comment]
You can also convert your .png file to an .ico using this website : https://redketchup.io/icon-converter

**Comment by unitycoder** [comment]
also to add as a workaround for now, can set custom icon to exe (from exe properties)
![image](https://github.com/unitycoder/UnityLauncherPro/assets/5438317/ab451d11-9cd6-4e70-9e8d-b7419fbaf467)

**Comment by SixParQuatre** [comment]
I'm personally using an color-inverted version of the unity hub icon.
![image](https://github.com/unitycoder/UnityLauncherPro/assets/103901485/0371c126-13ea-4e75-abe4-af1987844ef5)

**Comment by ltmx** [comment]
Just a few more ULP Icons I just made
![ULP Logo 13 White](https://github.com/unitycoder/UnityLauncherPro/assets/47640688/6b903c42-421a-44d0-a347-4632bd01b238)

![ULP Logo 13 Black](https://github.com/unitycoder/UnityLauncherPro/assets/47640688/2a33432c-5788-4401-a627-063f9787d590)

![ULP Logo 12 White@0 5x](https://github.com/unitycoder/UnityLauncherPro/assets/47640688/624fcd83-00e6-4b93-8d58-43cada37f0ff)

![ULP Logo 12 Black@0 5x](https://github.com/unitycoder/UnityLauncherPro/assets/47640688/b10d5cfc-5655-461a-9b43-7c08cbff84fb)

**Comment by SixParQuatre** [comment]
I'm also voting for the last one!

**Comment by unitycoder** [comment]
in that commit, added check for icon.ico file in the same folder as exe,
if icon file exists, its used as app/window and tray icon.

![image](https://github.com/user-attachments/assets/10a68bea-6e17-49e5-b373-9f0ff57d945e)
