### ISSUE TITLE
Freezing / Failing to install Editors, etc. 

### ISSUE THREAD

**Issue by nubbyninja** [unitycoder/UnityLauncherPro#128]
Brand new PC with Windows 11. 
Imported project via Unity version control launched from Unity Hub. 

Then close. Open Unity Launcher Pro, missing editor version...
Attempt to install editor version (2021.3.21f1)
Installer finishes. 
Attempt to launch.... missing editor version.

Currently stonewalled.

**Comment by unitycoder** [comment]
so the version is displayed as red, even after you installed that version? (and test also F5 to refresh list)

do you have the folder assigned (under which unity editor is installed)
![image](https://user-images.githubusercontent.com/5438317/231535091-1202b109-24e3-4846-aa51-4abba3c4b6bb.png)

**Comment by unitycoder** [comment]
unity hub default location:
C:\Program Files\Unity\Hub\Editor

could probably find that value from registry also.

**Comment by unitycoder** [comment]
if its still happening, can open again.
