### ISSUE TITLE
[Question][Suggestion] Version number of UnityLauncherPro somewhere in UI?

### ISSUE THREAD

**Issue by SixParQuatre** [unitycoder/UnityLauncherPro#130]
Since releases have slowed down, I have trouble remembering what's the last version I downloaded.
There's a 'View on GitHub' in Settings but I can't find the version number (e.g. 1.0.43) anywhere in the UI. Am I missing something? If not, can that be added somewhere ? 
Cheers

**Comment by unitycoder** [comment]
yes that would be very much needed.

i think last time i've tested it (in old launcher version),
but it required some extra setup to "feed" .txt file into VS project, that contained current build related info or something.

old launcher had update check button that would check latest releases from github,
https://github.com/unitycoder/UnityLauncher/commit/3591453fddc995d4f4e5459811e7b141f46576fe#diff-bd0da55621abfbed05468952f2d2690a26b504e071f4fa38a6dd3924db315accR1091

but would be nice to get that working here.

- [ ] how add auto-increment build version or date into VS project, using AppVeyor build system

**Comment by unitycoder** [comment]
now works with github builds, adds timestamp for current build (good enough for now..)
![image](https://github.com/unitycoder/UnityLauncherPro/assets/5438317/517e2f34-8c9b-4fbc-8ad9-aed18ad8fef6)

**Comment by SixParQuatre** [comment]
I think you can close this issue; it's definitely good enough for knowing if the most recent release on github is newer than the one currently installed.

**Comment by unitycoder** [comment]
thanks!
