### ISSUE TITLE
[Suggestion] Add a button to download the full editor from a browser

### ISSUE THREAD

**Issue by SixParQuatre** [unitycoder/UnityLauncherPro#131]
As discussed [here](https://github.com/unitycoder/UnityLauncherPro/issues/108#issuecomment-1352621328).

I'm adding a new issue since I think it got forgotten.

To recap: 
This is to replace/supplement 'Download in Browser' which downloads the web installer - which when run, downloads the full editor (+modules) but doesn't support pause/resume.

The Release Notes page now contains a direct link for the editor install (big 2.5+Gb); would it be possible to point to that ? Downloading that from a browser would better support pause/failure and resume; and would make cleaning up files easier.
FYI, the link is in the form of:
https://download.unity3d.com/download_unity/7d24041b62ee/Windows64EditorInstaller/UnitySetup64-2023.1.0a23.exe
vs the one the program currently goes to:
https://beta.unity3d.com/download/7d24041b62ee/UnityDownloadAssistant.exe

**Comment by unitycoder** [comment]
so it would be enough to open that link into browser?
that would be easiest, although then cannot launch that installer.. 

but i think that would be ok for now (*not sure how complicated it would be to add pause/resume support, but then you'd need some way to list current downloads, multiple downloads etc..)

**Comment by SixParQuatre** [comment]
Yes, that'd be perfectly fine - it's actually exactly what I want :)

**Comment by unitycoder** [comment]
not pretty but looks like this for now,
![image](https://github.com/unitycoder/UnityLauncherPro/assets/5438317/5ddd1d33-5a04-43cc-b9cb-2a9e01a15d12)

í'll make new build sometime soon (in a week or 2), but its available in the source code now.

**Comment by SixParQuatre** [comment]
Just pinging you on this for the promised new release :)

**Comment by unitycoder** [comment]
> Just pinging you on this for the promised new release :)

Oops! will do today.

**Comment by unitycoder** [comment]
new build available https://github.com/unitycoder/UnityLauncherPro/releases
