### ISSUE TITLE
exe dated 20/4/2024 seems to have a trojan in it

### ISSUE THREAD

**Issue by bugfinders** [unitycoder/UnityLauncherPro#148]
![image](https://github.com/unitycoder/UnityLauncherPro/assets/35536867/006f213d-7ee9-40ec-ad63-0389a2b4a1c9)

**Comment by unitycoder** [comment]
yup, false positives..

appears clean here just now:
https://www.virustotal.com/gui/url/e123b616cf4cbe3d3f7ba13b0d88cf5fff4638f72d5b9461088d0b11e9a41de3?nocache=1

**Comment by unitycoder** [comment]
i'll close this for now, since cannot do anything about it..

if that defender allows submitting false positive, can try doing that.

**Comment by bugfinders** [comment]
I also threw it to an online checker which also reported a virus. Hence i reported it to you. I will say it checked a bunch of av products only 1 (not defender) said virus.



On 25 Apr 2024, at 18:05, mika ***@***.***> wrote:

﻿

i'll close this for now, since cannot do anything about it..

if that defender allows submitting false positive, can try doing that.
