### ISSUE TITLE
new project = crashdump

### ISSUE THREAD

**Issue by bugfinders** [unitycoder/UnityLauncherPro#149]
No longer able to make new projects, it crash dumps, leaves a 20k suspended exe which wont die

[UnityLauncherPro.exe.12504.dmp](https://github.com/unitycoder/UnityLauncherPro/files/15055105/UnityLauncherPro.exe.12504.dmp)

**Comment by bugfinders** [comment]
Apparently its because i havent got urp downloaded and was selecting it - so the drop down list isnt checking that those options are installed. even though it listed 3d cross platform 17.0.10 or whatever as the option

**Comment by unitycoder** [comment]
ok reproduced here also, fails inside ExtractTar().

ill check

**Comment by unitycoder** [comment]
got it, there was updated version of that extractor here
https://gist.github.com/Matheos96/da8990030dfe3e27b0a48722042d9c0b
