### ISSUE TITLE
systray not opening as expected if opening new instance

### ISSUE THREAD

**Issue by bugfinders** [unitycoder/UnityLauncherPro#153]
Select minimize to systray, single instance only, minimize, not see it cos its hidden, launch, you see a flash of window and then nothing as old version is not triggered into restore as expected

**Comment by unitycoder** [comment]
yes, surprisingly complicated.. 
here is previous progress on that research (apparently need to do IPC messaging system)
https://github.com/unitycoder/UnityLauncherPro/issues/67

i'll close this one, so can follow or comment on up that older topic, thanks!

**Comment by bugfinders** [comment]
Id have thought some form of detect window or write pid to file then send restore to that window would work

On 30 May 2024, at 19:26, mika ***@***.***> wrote:

﻿

yes, surprisingly complicated..
here is previous progress on that research (apparently need to do IPC messaging system)
#67<https://github.com/unitycoder/UnityLauncherPro/issues/67>

i'll close this one, so can follow or comment on up that older topic, thanks!

**Comment by unitycoder** [comment]
yup, i tried that PID to File, but if i remember correctly, it required elevated rights to work properly..
