### ISSUE TITLE
Add Appimage or Flatpak Releases for Linux users

### ISSUE THREAD

**Issue by Mhowser** [unitycoder/UnityLauncherPro#154]
For appimages : https://appimage-builder.readthedocs.io/en/latest/hosted-services/github-actions.html

For Flatpak: https://docs.flatpak.org/en/latest/first-build.html

**Comment by Mhowser** [comment]
https://github.com/Ravbug/UnityHubNative

**Comment by unitycoder** [comment]
Is that appimage/flatpak something that works with WPF applications?
or was this posted in wrong repo? : )

**Comment by Mhowser** [comment]
I believe it does need to be compiled for the targeted operating system first, which might be out of the scope for this repo.
