### ISSUE TITLE
[bug] None of the Download cuttons in the Update tab work

### ISSUE THREAD

**Issue by SixParQuatre** [unitycoder/UnityLauncherPro#155]
Unity changed their release note/download site again, so the generated URLs are not correct anymore. 
This affects past releases as well  - I tested one from 6 months ago.
Release Notes button is unaffected; though there is a new #notes anchor that'd be cool to use.

**Comment by unitycoder** [comment]
did they really removed or hide the web installer also..huh?

*6000.0.5 still seems to have hidden web installer, but sounds like they want to get rid of it and force hub installs only..
https://beta.unity3d.com/download/17028576122a/UnityDownloadAssistant-6000.0.5f1.exe

**Comment by unitycoder** [comment]
i think i got it working, can test the latest build.
https://github.com/unitycoder/UnityLauncherPro/releases/tag/1.0.47

**Comment by SixParQuatre** [comment]
Works well, thanks!
