### ISSUE TITLE
It crashes if it detects a certain version of Unity

### ISSUE THREAD

**Issue by ImanCol** [unitycoder/UnityLauncherPro#159]
It's been a while since I ran this utility, but I just saw that there was an update and it ran without problems, but when I was adding the folder where the Unity editors are saved, it closed and did not open again. I was moving some versions that I had installed (C:\Program Files\Unity\Hub\Editor: [5.2.3p2, 6000.0.11f1, Unity (if I'm not mistaken, it's 5.3.3f1)] the Unity folder (version 5.3.3f1) when I removed it, it opened again without problems-

![2024-07-26-17-44-57](https://github.com/user-attachments/assets/b2261add-e64b-4281-aa38-8646bbbdf2c6)
![image](https://github.com/user-attachments/assets/e053ac58-6472-4e38-9228-f0bb337cac66)

**Comment by ImanCol** [comment]
The version 5.3.3f1 that appears in UnityLauncherPro is in another folder (C:\Program Files\Unity\Editor), this one is detected

**Comment by ImanCol** [comment]
Even though I have the same version  5.3.3f1 in different folders, the version inside "Hub/editor/" is still causing UnityLauncherPro to crash or not start

**Comment by unitycoder** [comment]
triedding installing 5.3.3f1 and tested duplicating that folder in another path, didn't manage to get crash or hangs,
but having same Unity version twice is not really supported, so it might cause unknown issues..

if you are able to download unitylauncher source code and run it in VisualStudio,
you might see where the crash is happening?

**Comment by ImanCol** [comment]
> tried installing 5.3.3f1 and tested duplicating that folder in another path, didn't manage to get crash or hangs, but having same Unity version twice is not really supported, so it might cause unknown issues..
> 
> if you are able to download unitylauncher source code and run it in VisualStudio, you might see where the crash is happening?


sorry, my VS is in spanish.
![image](https://github.com/user-attachments/assets/7760fae9-3848-4365-9664-6e7606bbe3c7)
System.NullReferenceException: 'Object reference not set to an instance of an object.'

System.Diagnostics.FileVersionInfo.ProductName.get returned null.

**Comment by ImanCol** [comment]
I have added a line to print path
Console.WriteLine("path: " + path);


path: C:\Program Files\Unity\Editor\Uninstall.exe
path: C:\Program Files\Unity\Hub\Editor\5.2.3p2\Editor\Uninstall.exe
path: C:\Program Files\Unity\Hub\Editor\5.3.3f1\Editor\Uninstall.exe
System.Diagnostics.FileVersionInfo.ProductName.**get** devolvió null.

I didn't know it was looking for the version in the uninstall file

**Comment by ImanCol** [comment]
path: C:\Program Files\Unity\Editor\Uninstall.exeFile:             C:\Program Files\Unity\Editor\Uninstall.exe
InternalName:     
OriginalFilename: 
FileVersion:      5.3.3.0
FileDescription:  Unity 5.3.3f1 Installer
Product:          Unity 5.3.3f1 (64-bit)
ProductVersion:   
Debug:            False
Patched:          False
PreRelease:       False
PrivateBuild:     False
SpecialBuild:     False
Language:         Independiente del idioma

El subproceso 0x15d68 terminó con código 0 (0x0).
El subproceso 0x15d70 terminó con código 0 (0x0).
El subproceso 0x15e88 terminó con código 0 (0x0).
El subproceso 0x15e8c terminó con código 0 (0x0).
El subproceso 0x15e54 terminó con código 0 (0x0).
El subproceso 0x15e5c terminó con código 0 (0x0).
El subproceso 0x15e60 terminó con código 0 (0x0).
path: C:\Program Files\Unity\Editor\Uninstall.exeFile:             C:\Program Files\Unity\Editor\Uninstall.exe
InternalName:     
OriginalFilename: 
FileVersion:      5.3.3.0
FileDescription:  Unity 5.3.3f1 Installer
Product:          Unity 5.3.3f1 (64-bit)
ProductVersion:   
Debug:            False
Patched:          False
PreRelease:       False
PrivateBuild:     False
SpecialBuild:     False
Language:         Independiente del idioma

path: C:\Program Files\Unity\Hub\Editor\5.2.3p2\Editor\Uninstall.exeFile:             C:\Program Files\Unity\Hub\Editor\5.2.3p2\Editor\Uninstall.exe
InternalName:     
OriginalFilename: 
FileVersion:      5.2.3.0
FileDescription:  Unity 5.2.3p2 Installer
Product:          Unity 5.2.3p2 (64-bit)
ProductVersion:   
Debug:            False
Patched:          False
PreRelease:       False
PrivateBuild:     False
SpecialBuild:     False
Language:         Independiente del idioma

path: C:\Program Files\Unity\Hub\Editor\5.3.3f1\Editor\Uninstall.exeFile:             C:\Program Files\Unity\Hub\Editor\5.3.3f1\Editor\Uninstall.exe
InternalName:     
OriginalFilename: 
FileVersion:      
FileDescription:  
Product:          
ProductVersion:   
Debug:            False
Patched:          False
PreRelease:       False
PrivateBuild:     False
SpecialBuild:     False
Language:         

System.Diagnostics.FileVersionInfo.ProductName.**get** devolvió null.

**Comment by unitycoder** [comment]
interesting, on my pc, it has productname,
can you check properties from that uninstall.exe in Explorer?
![image](https://github.com/user-attachments/assets/52ae1d68-008f-48fb-87d3-85e6ae93a4f5)

it uses uninstall.exe because Unity.exe doesnt contain proper version number..

**Comment by ImanCol** [comment]
I found that it is empty, I can't explain why...
![Captura de pantalla 2024-08-02 011450.png](https://github.com/user-attachments/assets/080491e2-88f3-48b5-8aa7-d64583ad5fad)

![Captura de pantalla 2024-08-02 011715.png](https://github.com/user-attachments/assets/34a38f2f-29dc-4587-9da8-115723f40767)

![Captura de pantalla 2024-08-02 011545.png](https://github.com/user-attachments/assets/906b86d5-5017-4370-a16c-ed5fbca0b001)

**Comment by ImanCol** [comment]
I found that it is empty, I can't explain why...
![Captura de pantalla 2024-08-02 011450.png](https://github.com/user-attachments/assets/080491e2-88f3-48b5-8aa7-d64583ad5fad)

![Captura de pantalla 2024-08-02 011715.png](https://github.com/user-attachments/assets/34a38f2f-29dc-4587-9da8-115723f40767)

![Captura de pantalla 2024-08-02 011545.png](https://github.com/user-attachments/assets/906b86d5-5017-4370-a16c-ed5fbca0b001)


Would there be a way to add an exception so that the program runs at least, showing something like version "unknown"

**Comment by unitycoder** [comment]
Yes, i'll add some null check, so at least it wont crash. (and could check for "product" field,
since in your debug print, it showed " Product: Unity 5.3.3f1 (64-bit)".

Some other users mentioning missing exe details, he had "ground exe" virus (that modifies exe files)
https://answers.microsoft.com/en-us/windows/forum/all/most-of-my-exe-files-details-file-version/cea8d658-c993-4a5f-b828-c1e8bbf6984b

**Comment by ImanCol** [comment]
I agree that upgrading to Windows 11 has been a bad experience.

Well, I will try to copy the uninstall file of the Unity 5 version that I have in another folder. 

You can close this if you get to commit a commit, with this exception resolved.
Thank you very much for solving my doubts.

**Comment by unitycoder** [comment]
Thanks! i'll close this after i add the null check.

**Comment by unitycoder** [comment]
this one is bit of a mystery,
> Product: Unity 5.3.3f1 (64-bit)
> ProductVersion:

where is "Product" field coming from,
its not in FileVersionInfo
https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.fileversioninfo?view=netframework-4.8

![image](https://github.com/user-attachments/assets/7f8809dc-4b90-4a11-a885-222751a854de)

**Comment by unitycoder** [comment]
the null check was added while ago, so closing this.. Can open again if still happens or find more info.
