### ISSUE TITLE
Clicking on New Project opens settings

### ISSUE THREAD

**Issue by Legi428** [unitycoder/UnityLauncherPro#175]
The latest build opens the settings page when I click on New Project. I haven't looked deeply, but I did not see it open the new project popup ever.

**Comment by unitycoder** [comment]
its a feature, if you haven't assigned any unity installation folders or missing root folder for new projects.

Definitely need to add some status message/popup about that!

**Comment by Legi428** [comment]
Ohh yes that was it! I must've deleted my configuration when I tested other things and I forgot to set my default folder. Yes good point on adding something so it's clear to the user.

**Comment by unitycoder** [comment]
latest build now has red warning text,
ideally the missing field textbox could be highlighted and focused too.

![image](https://github.com/user-attachments/assets/17c81eb9-96ca-4cad-9f44-18d3234f7431)
