### ISSUE TITLE
Custom Themes

### ISSUE THREAD

**Issue by GamingCrafthd** [unitycoder/UnityLauncherPro#18]
Add support for custom themes/color palettes like in Visual Studio.

![](https://visualstudioplatformteam.gallerycdn.vsassets.io/extensions/visualstudioplatformteam/visualstudio2017colorthemeeditor/15.5.0/1551144167238/274665/1/ColorThemeEditor-700.png)

Easiest way to save these themes would be using json with this framework: [Newtonsoft's Json.NET](https://www.newtonsoft.com/json)

**Comment by unitycoder** [comment]
sounds good.

some ideas what needs to be done:
- [ ] put rest of the styles/colors in one place, to have full list, like https://github.com/unitycoder/UnityLauncherPro/blob/master/UnityLauncherPro/Resources/Colors.xaml
- [ ] Settings tab: add dropdown that lists json files in Themes folder or so. (with none or default selected initially, which is no theme loaded)
- [ ] add settings value for currently selected theme filename
- [ ] load theme colors and apply at Start

**Comment by unitycoder** [comment]
ok some progress here, can load colors from simple .ini file (not enabled yet, until i add settings toggle for it)
https://github.com/unitycoder/UnityLauncherPro/commit/a40de0f55f71c55cdde0a0dc1f7a1482e2ac3d5a

**Comment by unitycoder** [comment]
color theme info *there is no build yet, but latest commit enabled these features
https://github.com/unitycoder/UnityLauncherPro/wiki/Custom-themes

**Comment by unitycoder** [comment]
first version is live, with latest build. can check how it works.
