### ISSUE TITLE
project list: platform display and selection

### ISSUE THREAD

**Issue by unitycoder** [unitycoder/UnityLauncherPro#19]
like in hub, you can open project in another platform
(and also should be able to see whats the current platform, in hub you cannot easily)

Things ToDo:
- [x] get current platform for the project
- [x] get list of installed platforms for that specific unity version (this is available in unity.Platforms already)
- [x] display those installed platforms in the dropdown menu (Platform column)
- [x] set current platform as selected in the dropdown menu
- [x] user can select another platform from dropdown menu
- [x] make dictionary of all platform names (to match commandline buildtarget params)
- [x] cleanup combobox style template and colors
- [x] when project is launched, set -buildTarget ...... based on the selected dropdown item
- [x] set theme colors for combobox, so can customize it
- [x] Need to refresh project platform at some point (otherwise shows old platform, if had changed it in the editor)
- [x] Manual Refresh loses started Process reference, need to keep it for Process.Exited() event

![image](https://user-images.githubusercontent.com/5438317/97857806-eee61f00-1d06-11eb-99f7-457d44bbda2d.png)

**Comment by unitycoder** [comment]
how to detect platform?
- not working anymore : http://answers.unity.com/answers/317348/view.html
- Assembly-CSharp.csproj has built target info: <UnityBuildTarget>StandaloneWindows64:19</UnityBuildTarget>
- somewhere else?

**Comment by unitycoder** [comment]
to set platform from commandline arguments:
`-buildTarget <name>
Select an active build target before loading a project. Possible options are:  Standalone, Win, Win64, OSXUniversal, Linux64, iOS, Android, WebGL, XboxOne, PS4, WindowsStoreApps, Switch, tvOS.`
https://docs.unity3d.com/Manual/CommandLineArguments.html

**Comment by dimmduh** [comment]
Quite old, but maybe helps
https://answers.unity.com/questions/317295/which-file-determines-build-platform.html

**Comment by unitycoder** [comment]
thanks, EditorUserBuildSettings.asset  is also binary file and different between unity versions so its difficult to parse properly..

currently reading it from "Assembly-CSharp.csproj" (if available)
https://github.com/unitycoder/UnityLauncherPro/blob/249fc453fab220f4cbeef755f3dc61bdfec7f416/UnityLauncherPro/Tools.cs#L727

**Comment by dimmduh** [comment]
thx
btw, I would be great if search all projects on hdd, not only opened by unity, but Assembly-CSharp.csproj is not exists in this case.

**Comment by unitycoder** [comment]
that could be interesting to try.. worried that it would be too slow with hundreds of projects and folders?
(of course could be running the background, or show cached results first, and be optional..)
it could solve this one then also: https://github.com/unitycoder/UnityLauncherPro/issues/27

and for the EditorUserBuildSettings.asset would need to reverse engineer the format.. unless unity would reveal some info if asked. (could try ask)

*also while ago literally had to make one tool, for searching source code files through lots of folders,
since explorer search is so slow.. every now and then just need to find that old project too..
https://github.com/unitycoder/FindInFiles

**Comment by unitycoder** [comment]
dropdownmenu item for datagrid
https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.datagridcomboboxcolumn?view=netframework-4.6.1

now.. how to bind that with these lists of strings, for each unity version..
```
// 5.6 : win32, win64, osx, linux, linux64, ios, android, web, webstreamed, webgl, xboxone, ps4, psp2, wsaplayer, tizen, samsungtv
// 2017: standalone, Win, Win64, OSXUniversal, Linux, Linux64, LinuxUniversal, iOS, Android, Web, WebStreamed, WebGL, XboxOne, PS4, PSP2, WindowsStoreApps, Switch, WiiU, N3DS, tvOS, PSM
// 2018: standalone, Win, Win64, OSXUniversal, Linux, Linux64, LinuxUniversal, iOS, Android, Web, WebStreamed, WebGL, XboxOne, PS4, WindowsStoreApps, Switch, N3DS, tvOS
// 2019: Standalone, Win, Win64, OSXUniversal, Linux64, iOS, Android, WebGL, XboxOne, PS4, WindowsStoreApps, Switch, tvOS
// 2020: Standalone, Win, Win64, OSXUniversal, Linux64, iOS, Android, WebGL, XboxOne, PS4, WindowsStoreApps, Switch, tvOS
```

**Comment by unitycoder** [comment]
now it kind of works, test it out. (might still have issues with older unity versions 5.6 - 2018)
![unitylauncherpro_platform](https://user-images.githubusercontent.com/5438317/119718610-709ec500-be70-11eb-8213-754deea24cbc.gif)

**Comment by unitycoder** [comment]
missing 2 more:
```
                                            <SolidColorBrush Color="#FF171717" />
                                        </Border.BorderBrush>
                                        <Border.Background>
                                            <!--combobox dropdown background here -->
                                            <SolidColorBrush Color="#FF2E2E34" />
```

**Comment by unitycoder** [comment]
added one more step,
"Need to refresh project platform at some point (otherwise shows old platform, if had changed it in the editor)"

**Comment by unitycoder** [comment]
seems that "Assembly-CSharp.csproj" buildtarget is NOT updated, unless you open visual studio.
`<UnityBuildTarget>StandaloneWindows64:19</UnityBuildTarget>`

doesn't work
- open project
- switch to 32bit or 64bit build
- exit unity
- Assembly-CSharp.csproj is not updated (contains old buildtarget)

works
- open project
- switch to 32bit or 64bit build
- do File/Save project or open c# project
- exit unity
- Assembly-CSharp.csproj is updated (contains new buildtarget)

**Comment by unitycoder** [comment]
^ that issue still happens, but no workarounds, until unity has this info somewhere else available..
