### ISSUE TITLE
Add button to open Application.persistentDataPath in explorer

### ISSUE THREAD

**Issue by dimmduh** [unitycoder/UnityLauncherPro#26]
It depends of project
Application.persistentDataPath

**Comment by unitycoder** [comment]
good idea.
just need to parse `<companyname>` and `<productname>` info somewhere.

https://docs.unity3d.com/ScriptReference/Application-persistentDataPath.html

**Comment by unitycoder** [comment]
ok it should be working now
https://github.com/unitycoder/UnityLauncherPro/commit/f8343ca59b26330dcd56124de53b8dd6432d91af
