### ISSUE TITLE
Add tab to view all Unity Projects caches

### ISSUE THREAD

**Issue by studentutu** [unitycoder/UnityLauncherPro#72]
Fo example 
WIndows :
%AppData%\..\Local\CrashDumps
%AppData%\..\Local\Unity\cache
%AppData%\..\LocalLow\Unity\Caches\GiCache

Not sure about other platforms.

**Comment by unitycoder** [comment]
yeah, would be easy (and this is only on windows platform for now)

**Comment by unitycoder** [comment]
next build has these buttons,
![image](https://user-images.githubusercontent.com/5438317/159770737-61c8cdb1-86de-4bbd-8ace-5b585aefd61e.png)

https://github.com/unitycoder/UnityLauncherPro/commit/c4a32427888124ce9d410e41fd19e35368d9a342

**Comment by studentutu** [comment]
@unitycoder  you rock! Thank you!

**Comment by studentutu** [comment]
@unitycoder  there is also %AppData%..\Roaming\Unity  - place for assets from asset store

**Comment by unitycoder** [comment]
yeah this folder is already in, that asset packages button: AppData\Roaming\Unity\Asset Store-5.x
