### ISSUE TITLE
add option install missing unity version

### ISSUE THREAD

**Issue by unitycoder** [unitycoder/UnityLauncherPro#89]
it was available in the older launcher version, could add it back..
currently there is only "download in browser" button, if version is missing during launch.

todo
- [x] add download & install button
- [x] get download url and download to temp *actually this is different url from "download in browser"-url
- [ ] run silent installer from temp, example: "C:\Users\USERNAME\AppData\Local\Temp\asdf.tmp\UnitySetup64.exe" -UI=reduced /D=C:\Program Files\Unity2023_1
- [x] delete temp file

later extras
- where set modules that you want to install?
- option to set folder where its installed 
- option to replace existing unity version (so it takes install folder from that, and could take same modules also)

**Comment by SixParQuatre** [comment]
As a note, I think an alternative for this would be to have an option in the  context menu of the Projects 'Find Version' which
1. copies the unity version like Copy Unity  Version
2. switches to the Update tab and paste the value in the search field.
This  would do 90% of the job, so it's be a good stop-gap solution until a fuller one gets in place,

**Comment by unitycoder** [comment]
just adding note:
Current that "Check Updates" is only in the Editors tab.

Could add it into recent projects context menu,
but also want to keep that list minimum.. so still thinking how to arrange those.

**Comment by unitycoder** [comment]
added download & install button for "upgrade project" window:
(it also copies root folder path to clipboard, so can paste in the unity installer window)

![image](https://user-images.githubusercontent.com/5438317/207602625-bd3ec77f-3ab1-4674-8809-2887b439dc9d.png)
https://github.com/unitycoder/UnityLauncherPro/commit/f6bab9ec2cd52f6338434146202417500b96daf1

**Comment by unitycoder** [comment]
now in updates tab also,
![image](https://user-images.githubusercontent.com/5438317/207686011-99068a02-4c25-494c-8816-663925a42a85.png)

**Comment by unitycoder** [comment]
download & install is now available on main build
