### ISSUE TITLE
Separate major versions in the "Updates" tab to see the last minor version we can download

### ISSUE THREAD

**Issue by Mythique** [unitycoder/UnityLauncherPro#91]
My most needed use case for the "Updates" section would be to see if a new minor version is out for the current major version I use. For example one of my project is in 2020.3.38. I would like to know rapidly if 2020.3.39 is out.

Currently the "Updates" section makes it a bit hard to see at a quick glance. Sorting the entries by release date mixes the versions together, and sorting the entries by version name does not work (5.0.0 is the first entry).

Thinking about this I see multiple solutions that could be implemented (I unfortunately still don't know what would be the best one) :
- Having sections betweens the entries. For example we would have a section "2020.3.x" that would list "2020.3.39", "2020.3.38", etc. Sorted by release date.
- Having another section on top, outside of the currrent entries. That would only list the last LTS and/or Tech versions. For example we would have 2021.3.10, 2020.3.39, 2019.4.40 for LTS and 2022.1.17 for Tech.

Maybe a combination of both solutions could work.

Let me know what you think. I am opened to discuss, and maybe contribute.

**Comment by Mythique** [comment]
Of course after writing this I noticed that there is a "Check Updates" button in the "Editors" tab. This will definitely help for my use case.

**Comment by unitycoder** [comment]
yeah, have thought about some ready filters on that page (like checkbox or dropdown to show only "alphas, betas, LTSs")

Currently can also search the updates with letter "a" for alphas,
or by version start string: 2020.3 (to list all of those 2020.3.x)

Sorting will be fixed eventually on all tabs, now that i got it working better in the projects list while ago.

TODO
- [ ] fix updates tab sorting by unity version
- [ ] add dropdown or checkboxes for quick filters (alpha, beta, LTS)
- [ ] add option to use human friendly release date ("5 days ago")

**Comment by unitycoder** [comment]
looks like this now, if find issues can reopen this
![image](https://user-images.githubusercontent.com/5438317/193397357-530ab8da-5d97-4ba1-bc52-f1da71e7ec6f.png)

**Comment by Mythique** [comment]
Thanks a lot, that is definitely nicer.

I've also noticed that some versions are duplicated in this view (2020.3.39f1 for example).

**Comment by unitycoder** [comment]
yes, those are coming from unity (i guess they upload same build multiple times or something), going to remove duplicates soon.
