### ISSUE TITLE
Multiple Screens with different DPI not properly supported

### ISSUE THREAD

**Issue by Mythique** [unitycoder/UnityLauncherPro#92]
Hi,

I am using a two screen setup :
- First one at 2560x1440 with a 125% DPI size (my main screen in the windows settings)
- Second one at 1920x1080 with 100% DPI size

If the app is on the main screen, the text and UI is displayed properly. If I move the window to the second screen, the text and UI is blurry :

![image](https://user-images.githubusercontent.com/4488088/192297799-4dbc293f-8e6c-4603-b96e-54289ee61395.png)

![image](https://user-images.githubusercontent.com/4488088/192297379-46777afd-0596-4a1d-a06e-23f89fdc84b1.png)

**Comment by unitycoder** [comment]
ok this seems to work on a quick test, ill commit it here later
https://github.com/microsoft/WPF-Samples/blob/main/PerMonitorDPI/readme.md#enabling-per-monitor-dpi-for-your-app

**Comment by Mythique** [comment]
Thanks! It seems to have worked, I tested it  the UI is not blurry anymore.

Small issue though, the UI is being scaled at 125% on the screen where it should be 100%

Here is how it looks if both my screens are at 100% (how it should always look I guess) :
![image](https://user-images.githubusercontent.com/4488088/192602620-9b72736b-dd66-4bf3-95f1-2c2bf8e9d0f6.png)

And here how it looks like on the same screen, if my other screen has a 125% scaling :

![image](https://user-images.githubusercontent.com/4488088/192602744-25adc38f-3ef6-4eb3-ab22-399bfdea5f40.png)

**Comment by unitycoder** [comment]
ok noticed that now also.
another issue is:
depending on what display the window is closed, it saves that size into preferences and then opens with wrong size on another display next time.

**Comment by unitycoder** [comment]
available in main build now
