### ISSUE TITLE
Add "C:\Program Files\Unity\Hub\Editor" by default in Installation Folder

### ISSUE THREAD

**Issue by SixParQuatre** [unitycoder/UnityLauncherPro#93]
This way, people transitioning from UnityHub will see their existing installs by default; and onboarding will be a tad less confusing.

**Comment by unitycoder** [comment]
yeah that sounds useful.

could actually check if that folder exists, if not then default to "C:\Program Files\"
or maybe even check "D:\Program Files" or "D:\Program Files\Unity\Hub\Editor" if hub can be installed to d drive?

**Comment by unitycoder** [comment]
this is available in latest builds
