### ISSUE TITLE
[bug]Updates tab shows versions not yet available

### ISSUE THREAD

**Issue by SixParQuatre** [unitycoder/UnityLauncherPro#97]
For instance, today, 2021.3.12f1 shows up but the  release notes link throws a 404 and the installer goes to https://unity3d.com/get-unity/download/archive#installer-not-found---version-2021.3.12f1
![image](https://user-images.githubusercontent.com/103901485/197812060-38bc31a6-9b2d-4379-bfda-ef0075c92339.png)
Version is 1.0.38

**Comment by unitycoder** [comment]
yes, that's due to unity's own system.
Apparently sometimes they upload versions, but not make them public yet.
(then bit later the actual version is uploaded and made public)

so can consider it as 'early news' of coming versions : )

**Comment by SixParQuatre** [comment]
> yes, that's due to unity's own system. Apparently sometimes they upload versions, but not make them public yet. (then bit later the actual version is uploaded and made public)
Do you know how Unity Hub figures out how not to show them ?

> so can consider it as 'early news' of coming versions : )
That's cool :D but also... it kinds of lowers trust in the app? I can live with it, but less technical peeps who encounters this behaviour the first time  they want to use the update tab (and I think it's one of the big added value of this software), might just think it's broken and go back to the Hub, which would be a  shame.

**Comment by unitycoder** [comment]
it almost feels like that hub has hand picked versions listed there (as they are often late or missing latest releases)
and in hub sources, it seems to fetch some list from intranet server (not available outside)
![image](https://user-images.githubusercontent.com/5438317/198081634-91ea934c-e242-47cb-b481-6cbe81501d70.png)

i guess it could be easy to check some of the recent urls (if they are "active"), just afraid to add extra requests..
but lets see if anyone else notices these.

**Comment by SixParQuatre** [comment]
Anecdote: hilariously, this made me see that Unity has been trying **very** hard to release 2022.2.0f1: there were version popping up every 3 days for like a month and not until today was it made public
